### ISSUE TITLE
Fail to upload file

### ISSUE THREAD

**Issue by s3131212** [m-creations/docker-openwrt-ftp#3]
Hi, thanks for this awesome image. Listing directories and downloading files are working properly However, I can't upload the file to the ftp server, the speed is slow (2.5KB/sec, ftp outside of docker can goes up to 12MB/sec) and disconnect from server after uploading about 10KB. Could you help me? Thanks

docker-compse.yml
```
ftp-img:
  image: mcreations/ftp
  ports:
    - "11021:21"
    - "65000-65100:65000-65100"
  volumes:
    - ./www/img:/data/img
  environment:
    - FTP_USER=username
    - FTP_PASS=password
    - HOST=domain
```

No error log was printed. Thanks a lot
